version: '3.5'

services:
  
  backend:
    build: backend-example-docker/
    volumes:
      - ./backend-example-docker/logs.txt:/usr/src/app/logs.txt
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=salasana

  frontend:
    build: frontend-example-docker/
    ports:
      - 5000:5000

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: salasana
    container_name: db-example
    volumes:
      - ./database:/var/lib/postgresql/data