version: '3.5'

services:
  
  backend:
    build: backend-example-docker/
    volumes:
      - ./backend-example-docker/logs.txt:/usr/src/app/logs.txt
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=salasana
    ports:
      - 8000:8000

  frontend:
    build: frontend-example-docker/
    ports:
      - 5000:5000

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: salasana
    container_name: db-example

  proxy:
    image: nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80